name: Dropdown Example

on:
  workflow_dispatch:
    inputs:
      choice:
        description: "Select tool"
        required: true
        type: choice
        options:
          - Rubeus
          - Seeker
      input1:
        description: "Hostname to key on"
        required: true
      input2:
        description: "Domain to clone certificate from"
        required: true

jobs:
  build:
    runs-on: windows-2019

    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v2

