name: Dropdown Example

on:
  workflow_dispatch:
    inputs:
      choice:
        description: "Tool"
        required: true
        type: choice
        options:
          - Rubeus
          - Seeker
      input1:
        description: "Restrict execution of loader to hostname."
        required: true
      input2:
        description: "Domain to copy certificate from. Used to generate a self-signed certificate and digitally sign the loader."
        required: true

jobs:
  build:
    runs-on: windows-2019

    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build PositiveIntent
      run: |
        python build.py --file ${{ github.event.inputs.choice }}.exe --hostname ${{ github.event.inputs.input1 }} --domain ${{ github.event.inputs.input2 }} --delay 10

    - name: Upload Loader Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Loader
        path: PositiveIntent\bin\Release\
